 
title: Dumbgeons & Dragons Transcript Archive
description: Searchable transcripts for every episode of Dumbgeons and Dragons
baseurl: "/dumbdragons-scripts"
url: "https://russdmore-lgtm.github.io"
theme: null